Repository InnerCircle-ICD3/commerce-BE-mono, pull requests merged in 2025-06, with the labels that each got.

#17 docs(cart) : DDL 상의 order 테이블 변경(#16)
  docs/erd/dbdiagram-io.md
Labels: documentation

#21 [feat] 공통 코드(DB, Enum) 응답 DTO 추가
  src/main/kotlin/com/fastcampus/commerce/common/response/CodeResponse.kt
  src/main/kotlin/com/fastcampus/commerce/common/response/EnumResponse.kt
Labels: feat

#14 refactor: 멀티모듈에 세팅되어 있던 Auth 로직 추가
  build.gradle.kts
  src/main/kotlin/com/fastcampus/commerce/auth/HttpHeaderKeys.kt
  src/main/kotlin/com/fastcampus/commerce/auth/JwtProperties.kt
  src/main/kotlin/com/fastcampus/commerce/auth/TokenProvider.kt
  src/main/kotlin/com/fastcampus/commerce/auth/api/controller/AuthController.kt
  src/main/kotlin/com/fastcampus/commerce/auth/api/dto/AuthDto.kt
  src/main/kotlin/com/fastcampus/commerce/auth/api/service/AuthService.kt
  src/main/kotlin/com/fastcampus/commerce/auth/config/SecurityConfig.kt
  src/main/kotlin/com/fastcampus/commerce/auth/filter/JwtAuthenticationFilter.kt
  src/main/kotlin/com/fastcampus/commerce/auth/infrastructure/security/oauth/config/NaverOAuth2Properties.kt
  src/main/kotlin/com/fastcampus/commerce/auth/infrastructure/security/oauth/config/OAuth2ClientRegistrationConfig.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/oauth/CustomOAuth2FailureHandler.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/oauth/CustomOAuth2SuccessHandler.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/oauth/CustomOAuth2UserService.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/oauth/CustomUserPrincipal.kt
  src/main/kotlin/com/fastcampus/commerce/common/error/AuthErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/controller/UserController.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/dto/UserDto.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/service/UserService.kt
  src/main/resources/application.yml
  src/main/resources/auth.yml
Labels: feat

#23 [feat] Presigned URL 생성 구현
  src/main/kotlin/com/fastcampus/commerce/common/config/ConfigurationPropertiesConfig.kt
  src/main/kotlin/com/fastcampus/commerce/common/entity/BaseEntity.kt
  src/main/kotlin/com/fastcampus/commerce/common/error/CommonErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/common/error/CoreException.kt
  src/main/kotlin/com/fastcampus/commerce/common/error/ErrorMessage.kt
  src/main/kotlin/com/fastcampus/commerce/common/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/fastcampus/commerce/file/application/FileService.kt
  src/main/kotlin/com/fastcampus/commerce/file/application/request/GeneratePresignedUrlRequest.kt
  src/main/kotlin/com/fastcampus/commerce/file/application/response/GeneratePresignedUrlResponse.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/entity/FileMetadata.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/error/FileErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/model/DomainType.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/model/FilePath.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/model/FilePolicy.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/model/FileStatus.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/model/FileType.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/repository/FileMetadataRepository.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/repository/StorageContextKeyRepository.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/repository/UniqueIdGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/service/FilePathGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/service/FilePolicyProvider.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/service/FileReader.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/service/FileStore.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/service/UploadUrlGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/validator/FileNameValidator.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/validator/FilePolicyValidator.kt
  src/main/kotlin/com/fastcampus/commerce/file/domain/validator/FileValidator.kt
  src/main/kotlin/com/fastcampus/commerce/file/infrastructure/config/FilePolicyProperties.kt
  src/main/kotlin/com/fastcampus/commerce/file/infrastructure/config/S3Config.kt
  src/main/kotlin/com/fastcampus/commerce/file/infrastructure/idgenerator/UuidUniqueIdGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/file/infrastructure/pathgenerator/DefaultFilePathGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/file/infrastructure/s3/PresignedUrlGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/file/interfaces/FileController.kt
  src/main/kotlin/com/fastcampus/commerce/file/interfaces/request/GeneratePresignedUrlApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/file/interfaces/response/GeneratePresignedUrlApiResponse.kt
  src/main/resources/application.yml
  src/main/resources/config/auth.yml
  src/main/resources/config/db.yml
  src/main/resources/config/file.yml
  src/main/resources/config/logging.yml
  src/main/resources/config/secret.yml
  src/main/resources/config/web.yml
  src/main/resources/db/migration/V1__init_table.sql
  src/main/resources/logback/logback-dev.xml
  src/main/resources/logback/logback-prod.xml
  src/test/kotlin/com/fastcampus/commerce/common/error/GlobalExceptionHandlerTest.kt
  src/test/kotlin/com/fastcampus/commerce/file/application/FileServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/file/domain/service/FilePolicyProviderTest.kt
  src/test/kotlin/com/fastcampus/commerce/file/domain/service/FileReaderTest.kt
  src/test/kotlin/com/fastcampus/commerce/file/domain/service/FileStoreTest.kt
  src/test/kotlin/com/fastcampus/commerce/file/domain/validator/FileNameValidatorTest.kt
  src/test/kotlin/com/fastcampus/commerce/file/domain/validator/FilePolicyValidatorTest.kt
  src/test/kotlin/com/fastcampus/commerce/file/infrastructure/pathgenerator/DefaultFilePathGeneratorTest.kt
  src/test/kotlin/com/fastcampus/commerce/file/infrastructure/s3/PresignedUrlGeneratorTest.kt
  src/test/kotlin/com/fastcampus/commerce/file/interfaces/FileControllerTest.kt
Labels: feat

#30 feat(cart) : 장바구니 상품 추가(#18)
  src/main/kotlin/com/fastcampus/commerce/cart/application/CartItemService.kt
  src/main/kotlin/com/fastcampus/commerce/cart/application/TmpInventoryService.kt
  src/main/kotlin/com/fastcampus/commerce/cart/domain/entity/CartItem.kt
  src/main/kotlin/com/fastcampus/commerce/cart/infrastructure/repository/CartItemRepository.kt
  src/main/kotlin/com/fastcampus/commerce/cart/infrastructure/repository/TmpInventoryRepository.kt
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemController.kt
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemProtocol.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/error/ProductErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/repository/InventoryRepository.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/service/ProductReader.kt
  src/main/kotlin/com/fastcampus/commerce/product/infrastructure/InventoryRepositoryImpl.kt
  src/test/kotlin/com/fastcampus/commerce/cart/application/CartItemServiceTest.kt
Labels: feat

#35 [FIX] 장바구니 단위테스트 코드 수정
  src/main/kotlin/com/fastcampus/commerce/cart/application/CartItemService.kt
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemController.kt
  src/main/kotlin/com/fastcampus/commerce/product/infrastructure/InventoryJpaRepository.kt
  src/main/kotlin/com/fastcampus/commerce/product/infrastructure/InventoryRepositoryImpl.kt
  src/test/kotlin/com/fastcampus/commerce/cart/application/CartItemServiceTest.kt
Labels: bug

#43 [feat] 리뷰 수정 API 추가
  docs/api/openapi3.yaml
  src/main/kotlin/com/fastcampus/commerce/review/application/ReviewCommandService.kt
  src/main/kotlin/com/fastcampus/commerce/review/application/request/UpdateReviewRequest.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/entity/Review.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/error/ReviewErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/model/ReviewUpdater.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/repository/ReviewRepository.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/service/ReviewReader.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/service/ReviewStore.kt
  src/main/kotlin/com/fastcampus/commerce/review/infrastructure/ReviewRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/review/interfaces/ReviewController.kt
  src/main/kotlin/com/fastcampus/commerce/review/interfaces/request/UpdateReviewApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/review/interfaces/response/UpdateReviewApiResponse.kt
  src/test/kotlin/com/fastcampus/commerce/file/interfaces/FileControllerRestDocTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/application/ReviewCommandServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/domain/service/ReviewReaderTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/domain/service/ReviewStoreTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/interfaces/ReviewControllerRestDocTest.kt
Labels: feat

#49 feat(cart) : 장바구니 생성 테스트 코드 추가(#18)
  docs/api/openapi3.yaml
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemController.kt
  src/test/kotlin/com/fastcampus/commerce/cart/application/CartItemServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemControllerRestDocTest.kt
Labels: feat

#50 [feat] 상품 리뷰 관련 API 추가
  docs/api/openapi3.yaml
  src/main/kotlin/com/fastcampus/commerce/common/response/PagedData.kt
  src/main/kotlin/com/fastcampus/commerce/review/application/ProductReviewService.kt
  src/main/kotlin/com/fastcampus/commerce/review/application/response/ProductReviewRatingResponse.kt
  src/main/kotlin/com/fastcampus/commerce/review/application/response/ProductReviewResponse.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/model/ProductReview.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/model/ProductReviewRating.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/repository/ProductReviewRepository.kt
  src/main/kotlin/com/fastcampus/commerce/review/infrastructure/ProductReviewRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/review/interfaces/ProductReviewController.kt
  src/main/kotlin/com/fastcampus/commerce/review/interfaces/response/ProductReviewApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/review/interfaces/response/ProductReviewRatingApiResponse.kt
  src/test/kotlin/com/fastcampus/commerce/review/application/ProductReviewServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/interfaces/ProductReviewControllerRestDocTest.kt
Labels: feat

#52 feat(cart) : 장바구니 상품 조회 기능 구현 (#18)
  docs/api/openapi3.yaml
  src/main/kotlin/com/fastcampus/commerce/cart/application/CartItemService.kt
  src/main/kotlin/com/fastcampus/commerce/cart/infrastructure/repository/CartItemRepository.kt
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemController.kt
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemProtocol.kt
  src/main/kotlin/com/fastcampus/commerce/common/policy/DeliveryPolicy.kt
  src/test/kotlin/com/fastcampus/commerce/cart/application/CartItemServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemControllerRestDocTest.kt
Labels: feat

#55 Feat/18 delete cart
  docs/api/openapi3.yaml
  src/main/kotlin/com/fastcampus/commerce/cart/application/CartItemService.kt
  src/main/kotlin/com/fastcampus/commerce/cart/infrastructure/repository/CartItemRepository.kt
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemController.kt
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemProtocol.kt
  src/main/kotlin/com/fastcampus/commerce/common/policy/DeliveryPolicy.kt
  src/test/kotlin/com/fastcampus/commerce/cart/application/CartItemServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemControllerRestDocTest.kt
Labels: feat

#69 [feat] 배송지 단건 조회 및 기본 배송지 조회 기능 추가
  docs/api/openapi3.yaml
  src/main/kotlin/com/fastcampus/commerce/common/config/WebConfig.kt
  src/main/kotlin/com/fastcampus/commerce/common/util/PhoneNumberUtil.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/controller/UserAddressController.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/controller/request/RegisterUserAddressApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/controller/request/UpdateUserAddressApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/controller/response/DefaultAddressApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/service/UserAddressService.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/service/response/UserAddressResponse.kt
  src/main/kotlin/com/fastcampus/commerce/user/domain/repository/UserAddressRepository.kt
  src/test/kotlin/com/fastcampus/commerce/common/util/PhoneNumberUtilTest.kt
  src/test/kotlin/com/fastcampus/commerce/user/api/controller/UserAddressControllerRestDocTest.kt
  src/test/kotlin/com/fastcampus/commerce/user/api/service/UserAddressServiceTest.kt
Labels: feat

#71 [feat] 상품 카테고리 목록 조회 API 추가
  docs/api/openapi3.yaml
  src/main/kotlin/com/fastcampus/commerce/product/application/ProductQueryService.kt
  src/main/kotlin/com/fastcampus/commerce/product/application/response/CategoryResponse.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/model/CategoryDetail.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/repository/CategoryRepository.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/service/CategoryReader.kt
  src/main/kotlin/com/fastcampus/commerce/product/infrastructure/CategoryRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/product/interfaces/ProductController.kt
  src/main/kotlin/com/fastcampus/commerce/product/interfaces/response/CategoryApiResponse.kt
  src/main/resources/application.yml
  src/main/resources/config/auth.yml
  src/main/resources/config/db.yml
  src/test/kotlin/com/fastcampus/commerce/product/application/ProductQueryServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/product/interfaces/ProductControllerRestDocTest.kt
Labels: feat

#75 [feat] 주문 API 껍데기 추가
  .github/workflows/deploy.yml
  docs/api/openapi3.yaml
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/OrderController.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/request/OrderApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/request/PrepareOrderApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/request/SearchOrderApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/GetOrderApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/OrderApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/PrepareOrderApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/SearchOrderApiResponse.kt
  src/test/kotlin/com/fastcampus/commerce/order/interfaces/OrderControllerRestDocTest.kt
Labels: feat

#85 [feat] 장바구니
  src/main/kotlin/com/fastcampus/commerce/cart/application/CartItemService.kt
  src/main/kotlin/com/fastcampus/commerce/cart/application/TmpInventoryService.kt
  src/main/kotlin/com/fastcampus/commerce/cart/infrastructure/repository/TmpInventoryRepository.kt
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemController.kt
  src/main/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemProtocol.kt
  src/main/kotlin/com/fastcampus/commerce/common/config/WebConfig.kt
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/fastcampus/commerce/cart/application/CartItemServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/cart/interfaces/CartItemControllerRestDocTest.kt
Labels: feat

#86 [feat] 사용자/관리자 결제 API 추가
  docs/api/tag-descriptions.yml
  src/main/kotlin/com/fastcampus/commerce/admin/payment/application/AdminPaymentService.kt
  src/main/kotlin/com/fastcampus/commerce/admin/payment/interfaces/AdminPaymentController.kt
  src/main/kotlin/com/fastcampus/commerce/admin/payment/interfaces/reqeust/SearchAdminPaymentApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/admin/payment/interfaces/response/AdminPaymentApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/order/application/OrderPaymentService.kt
  src/main/kotlin/com/fastcampus/commerce/order/application/order/OrderService.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/entity/Order.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/entity/OrderStatus.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/error/OrderErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/repository/OrderPaymentRepository.kt
  src/main/kotlin/com/fastcampus/commerce/order/infrastructure/OrderJpaRepository.kt
  src/main/kotlin/com/fastcampus/commerce/order/infrastructure/OrderPaymentRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/payment/application/PaymentService.kt
  src/main/kotlin/com/fastcampus/commerce/payment/application/PaymentValidator.kt
  src/main/kotlin/com/fastcampus/commerce/payment/application/request/PaymentProcessRequest.kt
  src/main/kotlin/com/fastcampus/commerce/payment/application/response/PaymentProcessResponse.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/entity/Payment.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/error/PaymentErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/model/PgPaymentInfo.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/repository/PaymentRepository.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/service/PaymentReader.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/service/PgClient.kt
  src/main/kotlin/com/fastcampus/commerce/payment/infrastructure/MockPgClient.kt
  src/main/kotlin/com/fastcampus/commerce/payment/infrastructure/PaymentJpaRepository.kt
  src/main/kotlin/com/fastcampus/commerce/payment/infrastructure/PaymentRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/payment/interfaces/PaymentController.kt
  src/main/kotlin/com/fastcampus/commerce/payment/interfaces/request/PaymentApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/payment/interfaces/response/CancelPaymentApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/payment/interfaces/response/PaymentApiResponse.kt
  src/main/resources/db/migration/V1__init_table.sql
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/fastcampus/commerce/admin/payment/application/AdminPaymentServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/admin/payment/interfaces/AdminPaymentControllerRestDocTest.kt
  src/test/kotlin/com/fastcampus/commerce/order/application/OrderPaymentServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/payment/application/PaymentServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/payment/domain/service/PaymentReaderTest.kt
  src/test/kotlin/com/fastcampus/commerce/payment/interfaces/PaymentControllerRestDocTest.kt
Labels: feat

#76 Feat/28 auth config and custom user resolver
  src/main/kotlin/com/fastcampus/commerce/auth/TokenProvider.kt
  src/main/kotlin/com/fastcampus/commerce/auth/api/controller/AuthController.kt
  src/main/kotlin/com/fastcampus/commerce/auth/api/dto/AuthDto.kt
  src/main/kotlin/com/fastcampus/commerce/auth/api/service/AuthService.kt
  src/main/kotlin/com/fastcampus/commerce/auth/config/SecurityConfig.kt
  src/main/kotlin/com/fastcampus/commerce/auth/filter/JwtAuthenticationFilter.kt
  src/main/kotlin/com/fastcampus/commerce/auth/infrastructure/security/oauth/config/NaverOAuth2Properties.kt
  src/main/kotlin/com/fastcampus/commerce/auth/infrastructure/security/oauth/config/OAuth2ClientRegistrationConfig.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/annotation/WithRoles.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/oauth/CustomOAuth2FailureHandler.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/oauth/CustomOAuth2SuccessHandler.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/oauth/CustomOAuth2UserService.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/oauth/CustomUserPrincipal.kt
  src/main/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/resolver/RoleBasedUserArgumentResolver.kt
  src/main/kotlin/com/fastcampus/commerce/common/config/SnowflakeIdConfig.kt
  src/main/kotlin/com/fastcampus/commerce/common/config/WebConfig.kt
  src/main/kotlin/com/fastcampus/commerce/common/error/AuthErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/common/error/GlobalExceptionHandler.kt
  src/main/kotlin/com/fastcampus/commerce/common/id/IdGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/common/id/SnowflakeIdGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/controller/UserController.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/dto/UserDto.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/service/UserService.kt
  src/main/kotlin/com/fastcampus/commerce/user/domain/entity/User.kt
  src/main/kotlin/com/fastcampus/commerce/user/domain/enums/UserRole.kt
  src/main/kotlin/com/fastcampus/commerce/user/domain/repository/Oauth2ProviderRepository.kt
  src/main/kotlin/com/fastcampus/commerce/user/domain/repository/UserOauth2ConnectionRepository.kt
  src/main/kotlin/com/fastcampus/commerce/user/domain/repository/UserRepository.kt
  src/main/kotlin/com/fastcampus/commerce/user/domain/repository/UserRoleConnectionRepository.kt
  src/main/kotlin/com/fastcampus/commerce/user/domain/repository/UserRoleRepository.kt
  src/main/resources/config/db.yml
  src/test/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/resolver/RoleBasedUserArgumentResolverTest.kt
  src/test/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/resolver/SampleController.kt
Labels: feat

#82 Feat/79 order command
  src/main/kotlin/com/fastcampus/commerce/cart/application/query/CartItemReader.kt
  src/main/kotlin/com/fastcampus/commerce/cart/application/query/dto/CartItemDto.kt
  src/main/kotlin/com/fastcampus/commerce/cart/infrastructure/query/CartItemReaderImpl.kt
  src/main/kotlin/com/fastcampus/commerce/order/application/order/OrderService.kt
  src/main/kotlin/com/fastcampus/commerce/order/application/query/ProductSnapshotReader.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/entity/OrderStatus.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/repository/OrderItemRepository.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/repository/OrderRepository.kt
  src/main/kotlin/com/fastcampus/commerce/order/infrastructure/query/ProductSnapshotReaderImpl.kt
  src/main/kotlin/com/fastcampus/commerce/order/infrastructure/repository/ProductSnapshotRepository.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/OrderController.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/request/OrderApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/PrepareOrderApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/SearchOrderApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/entity/PaymentMethod.kt
Labels: feat

#90 [feat] 주문 취소 API 추가
  src/main/kotlin/com/fastcampus/commerce/order/application/order/OrderService.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/OrderController.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/CancelOrderApiResponse.kt
  src/main/resources/config/db.yml
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/fastcampus/commerce/auth/interfaces/web/security/resolver/RoleBasedUserArgumentResolverTest.kt
  src/test/kotlin/com/fastcampus/commerce/config/TestConfig.kt
  src/test/kotlin/com/fastcampus/commerce/order/interfaces/OrderControllerRestDocTest.kt
Labels: feat

#94 [feat] 메인 상품 조회 및 리뷰에 썸네일 추가
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/request/SearchOrderApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/product/application/MainProductService.kt
  src/main/kotlin/com/fastcampus/commerce/product/application/ProductQueryService.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/repository/ProductRepository.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/service/ProductReader.kt
  src/main/kotlin/com/fastcampus/commerce/product/infrastructure/ProductRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/product/interfaces/ProductController.kt
  src/main/kotlin/com/fastcampus/commerce/review/application/response/UserReviewResponse.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/model/ReviewInfoFlat.kt
  src/main/kotlin/com/fastcampus/commerce/review/infrastructure/ReviewAdminRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/review/infrastructure/UserReviewRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/review/interfaces/request/UserReviewApiResponse.kt
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/fastcampus/commerce/product/application/MainProductServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/product/domain/service/ProductReaderTest.kt
  src/test/kotlin/com/fastcampus/commerce/product/interfaces/ProductControllerRestDocTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/application/UserReviewServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/domain/service/ReviewAdminReaderTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/interfaces/UserReviewControllerRestDocTest.kt
Labels: feat

#98 Feat/88 admin order
  src/main/kotlin/com/fastcampus/commerce/admin/order/application/AdminOrderService.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/controller/AdminOrderController.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/request/AdminOrderCreateRequest.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/request/AdminOrderSearchRequest.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/request/AdminOrderUpdateRequest.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/response/AdminOrderCreateResponse.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/response/AdminOrderDetailResponse.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/response/AdminOrderListResponse.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/interfaces/AdminOrderQuery.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/interfaces/AdminOrderQueryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/entity/OrderItem.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/entity/OrderStatus.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/error/OrderErrorCode.kt
Labels: feat

#104 [feat] 결제완료시 재고 차감 로직 추가
  src/main/kotlin/com/fastcampus/commerce/order/application/OrderPaymentService.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/entity/Order.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/model/OrderProduct.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/repository/OrderPaymentRepository.kt
  src/main/kotlin/com/fastcampus/commerce/order/infrastructure/OrderPaymentRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/payment/application/PaymentService.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/entity/Payment.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/entity/PaymentStatus.kt
  src/main/kotlin/com/fastcampus/commerce/payment/domain/error/PaymentErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/entity/Inventory.kt
  src/main/kotlin/com/fastcampus/commerce/product/domain/service/ProductStore.kt
  src/test/kotlin/com/fastcampus/commerce/payment/application/PaymentServiceTest.kt
Labels: feat

#110 [feat] 상품 리뷰에 유저 필드 추가
  src/main/kotlin/com/fastcampus/commerce/admin/order/application/AdminOrderService.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/controller/AdminOrderController.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/request/AdminOrderCreateRequest.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/request/AdminOrderSearchRequest.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/request/AdminOrderUpdateRequest.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/response/AdminOrderCreateResponse.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/response/AdminOrderDetailResponse.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/response/AdminOrderListResponse.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/interfaces/AdminOrderQuery.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/interfaces/AdminOrderQueryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/common/id/UniqueIdGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/order/application/OrderPaymentService.kt
  src/main/kotlin/com/fastcampus/commerce/order/application/order/OrderService.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/model/OrderProduct.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/repository/OrderPaymentRepository.kt
  src/main/kotlin/com/fastcampus/commerce/order/infrastructure/OrderPaymentRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/payment/application/PaymentService.kt
  src/main/kotlin/com/fastcampus/commerce/review/application/response/ProductReviewResponse.kt
  src/main/kotlin/com/fastcampus/commerce/review/domain/model/ProductReviewFlat.kt
  src/main/kotlin/com/fastcampus/commerce/review/infrastructure/ProductReviewRepositoryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/review/interfaces/response/ProductReviewApiResponse.kt
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/fastcampus/commerce/payment/application/PaymentServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/application/ProductReviewServiceTest.kt
  src/test/kotlin/com/fastcampus/commerce/review/interfaces/ProductReviewControllerRestDocTest.kt
Labels: feat

#114 [feat] 주문 수정 및 아이디 생성 방식 수정
  src/main/kotlin/com/fastcampus/commerce/cart/application/query/dto/CartItemDto.kt
  src/main/kotlin/com/fastcampus/commerce/cart/infrastructure/query/CartItemReaderImpl.kt
  src/main/kotlin/com/fastcampus/commerce/common/id/UniqueIdGenerator.kt
  src/main/kotlin/com/fastcampus/commerce/order/application/order/OrderService.kt
  src/main/kotlin/com/fastcampus/commerce/order/application/query/ProductSnapshotReader.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/error/OrderErrorCode.kt
  src/main/kotlin/com/fastcampus/commerce/order/infrastructure/query/ProductSnapshotReaderImpl.kt
  src/main/kotlin/com/fastcampus/commerce/order/infrastructure/repository/ProductSnapshotRepository.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/request/OrderApiRequest.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/PrepareOrderApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/user/api/service/UserService.kt
Labels: feat

#120 [refactor] 관리자 주문 응답 API 포맷 변경
  build.gradle.kts
  src/main/kotlin/com/fastcampus/commerce/admin/order/application/AdminOrderService.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/request/AdminOrderSearchRequest.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/response/AdminOrderDetailResponse.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/infrastructure/response/AdminOrderListResponse.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/interfaces/AdminOrderQuery.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/interfaces/AdminOrderQueryImpl.kt
  src/main/kotlin/com/fastcampus/commerce/admin/order/interfaces/AdminOrderQueryRepository.kt
  src/main/kotlin/com/fastcampus/commerce/order/application/order/OrderService.kt
  src/main/kotlin/com/fastcampus/commerce/order/domain/entity/OrderStatus.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/GetOrderApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/order/interfaces/response/SearchOrderApiResponse.kt
  src/main/kotlin/com/fastcampus/commerce/payment/interfaces/request/PaymentCommandRequest.kt
  src/main/resources/static/swagger-ui/openapi3.yaml
  src/test/kotlin/com/fastcampus/commerce/admin/order/infrastructure/controller/AdminOrderControllerRestDocTest.kt
  src/test/kotlin/com/fastcampus/commerce/order/interfaces/OrderControllerRestDocTest.kt
Labels: refactor
